### ISSUE TITLE
Update dependencies on next release

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/jupyter-server-proxy-feedstock#19]
https://github.com/jupyterhub/jupyter-server-proxy/pull/254

**Comment by bollwyvl** [comment]
Let's try to get it this time... PR incoming...

**Comment by jakirkham** [comment]
Actually think this was already done in PR ( https://github.com/conda-forge/jupyter-server-proxy-feedstock/pull/20 )

**Comment by jakirkham** [comment]
Though please feel free to reopen if we missed something

**Comment by bollwyvl** [comment]
never ends, my friend :crying_cat_face:

**Comment by jakirkham** [comment]
Update happening in PR ( https://github.com/conda-forge/jupyter-server-proxy-feedstock/pull/23 )
